name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run unit tests
      run: npm run test:unit

    - name: Run storybook
      run: npm run storybook
    
    - name: Run screenshot tests
      run: npm run test:screen
